import Sidebar from "../components/Sidebar";
import Navbar from "../components/Navbar";
import Footer from "../components/Footer";

const TermsOfService = () => {
  return (
    <div className="h-screen flex bg-[#0b1220] overflow-hidden">
      
      {/* Sidebar */}
      <Sidebar />

      {/* Main Content */}
      <div className="flex-1 flex flex-col">

        {/* Navbar */}
        <div className="h-16">
          <Navbar />
        </div>

        {/* Body */}
        <div className="flex-1 p-4 bg-[#111827] flex flex-col overflow-hidden">



          {/* Main Content Area (Dark Gradient) */}
          <div className="flex-1 rounded-md shadow bg-gradient-to-b from-[#0f172a] to-[#020617] border border-white/10 p-8 overflow-y-auto w-full text-gray-300">
            <h1 className="text-3xl font-bold text-white mb-6">Terms of Service</h1>
            
            <p className="mb-4">
              Welcome to PrepAI. By accessing or using our platform, you agree to be bound by these Terms of Service. Please read them carefully before utilizing our services.
            </p>

            <h2 className="text-xl font-semibold text-white mt-8 mb-4">1. Acceptance of Terms</h2>
            <p className="mb-4">
              By creating an account and using the PrepAI platform, you acknowledge that you have read, understood, and agree to be bound by these Terms, as well as our Privacy Policy.
            </p>

            <h2 className="text-xl font-semibold text-white mt-8 mb-4">2. Description of Service</h2>
            <p className="mb-4">
              PrepAI provides AI-powered interview preparation tools, including mock interviews, coding assessments, resume analysis, and performance analytics. We act as an educational platform to help you improve your interview skills.
            </p>

            <h2 className="text-xl font-semibold text-white mt-8 mb-4">3. User Responsibilities</h2>
            <ul className="list-disc list-inside mb-4 space-y-2 opacity-90">
              <li>You must provide accurate and complete information when registering an account.</li>
              <li>You are responsible for safeguarding your account password and activity.</li>
              <li>You agree not to misuse the platform (e.g., attempt unauthorized access, upload malicious code, or manipulate AI endpoints).</li>
            </ul>

            <h2 className="text-xl font-semibold text-white mt-8 mb-4">4. AI Analysis and Disclaimer</h2>
            <p className="mb-4">
              The feedback, scores, and analytics provided by PrepAI are generated by artificial intelligence models. While we strive for accuracy, we do not guarantee that AI judgments are perfectly objective or entirely correct. PrepAI's feedback should be used for educational purposes and not as a definitive professional evaluation.
            </p>

            <h2 className="text-xl font-semibold text-white mt-8 mb-4">5. Account Termination</h2>
            <p className="mb-4">
              We reserve the right to suspend or terminate your account at our sole discretion, without prior notice or liability, for any reason whatsoever, including if you breach these Terms of Service.
            </p>

            <h2 className="text-xl font-semibold text-white mt-8 mb-4">6. Changes to Terms</h2>
            <p className="mb-4">
              We reserve the right to modify these terms at any time. If changes are material, we will try to provide at least 30 days' notice before the new terms turn effective.
            </p>

            <div className="mt-12 pt-6 border-t border-white/10 text-sm text-gray-500 flex justify-between">
              <span>Last updated: April 2, 2026</span>
              <span>terms@prepai.com</span>
            </div>
          </div>

        </div>

        {/* Sticky Footer */}
        <Footer />

      </div>
    </div>
  );
};

export default TermsOfService;